//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin_trazabilidad.Paginas.Catalogos
{


    public partial class Frm_Apl_Entidad_Empresa
    {
    }
}
