//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apl_Empresas()
        {
            this.Apl_Roles = new HashSet<Apl_Roles>();
            this.Apl_Sucursales = new HashSet<Apl_Sucursales>();
            this.Apl_Usuarios = new HashSet<Apl_Usuarios>();
            this.Apl_Notificaciones = new HashSet<Apl_Notificaciones>();
            this.Tra_Cat_Config_Items_Table_Show = new HashSet<Tra_Cat_Config_Items_Table_Show>();
            this.Cat_Con_Cuentas_Contables = new HashSet<Cat_Con_Cuentas_Contables>();
            this.Cat_Con_Cuentas_Contables_Sat = new HashSet<Cat_Con_Cuentas_Contables_Sat>();
            this.Apl_Menus_Empresa = new HashSet<Apl_Menus_Empresa>();
            this.Cat_Con_Impuestos_Cuentas_Contables_CC = new HashSet<Cat_Con_Impuestos_Cuentas_Contables_CC>();
            this.Cat_Nom_Regimen_Fiscal = new HashSet<Cat_Nom_Regimen_Fiscal>();
            this.Cat_Con_Niveles = new HashSet<Cat_Con_Niveles>();
            this.Cat_Nom_Departamentos = new HashSet<Cat_Nom_Departamentos>();
            this.Cat_Nom_Departamentos1 = new HashSet<Cat_Nom_Departamentos>();
            this.Cat_Con_Centro_Costos = new HashSet<Cat_Con_Centro_Costos>();
            this.Apl_Pos_Accesos = new HashSet<Apl_Pos_Accesos>();
            this.Apl_Parametros_Facturas = new HashSet<Apl_Parametros_Facturas>();
        }
    
        public int Empresa_ID { get; set; }
        public int Estatus_ID { get; set; }
        public int Entidad_Empresa_ID { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public string RFC { get; set; }
        public string CP { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Comentarios { get; set; }
        public byte[] Ruta_Imagen { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public string Calle { get; set; }
        public string No_Exterior { get; set; }
        public string No_Interior { get; set; }
        public string Localidad { get; set; }
        public string Pais { get; set; }
        public string Nombre_Carpeta { get; set; }
        public Nullable<int> Pais_ID { get; set; }
        public Nullable<int> Estado_ID { get; set; }
        public Nullable<int> Localidad_ID { get; set; }
        public Nullable<int> Codigo_Postal_ID { get; set; }
        public Nullable<int> Municipio_Localidad_ID { get; set; }
        public Nullable<int> Ciudad_ID { get; set; }
    
        public virtual Apl_Entidades_Empresas Apl_Entidades_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Roles> Apl_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Sucursales> Apl_Sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Usuarios> Apl_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Notificaciones> Apl_Notificaciones { get; set; }
        public virtual Cat_Nom_Ciudades Cat_Nom_Ciudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tra_Cat_Config_Items_Table_Show> Tra_Cat_Config_Items_Table_Show { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Cuentas_Contables> Cat_Con_Cuentas_Contables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Cuentas_Contables_Sat> Cat_Con_Cuentas_Contables_Sat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Menus_Empresa> Apl_Menus_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Impuestos_Cuentas_Contables_CC> Cat_Con_Impuestos_Cuentas_Contables_CC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Nom_Regimen_Fiscal> Cat_Nom_Regimen_Fiscal { get; set; }
        public virtual Cat_Nom_Localidades Cat_Nom_Localidades { get; set; }
        public virtual Cat_Nom_Municipios_Localidades Cat_Nom_Municipios_Localidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Niveles> Cat_Con_Niveles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Nom_Departamentos> Cat_Nom_Departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Nom_Departamentos> Cat_Nom_Departamentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Centro_Costos> Cat_Con_Centro_Costos { get; set; }
        public virtual Cat_Nom_Codigos_Postales Cat_Nom_Codigos_Postales { get; set; }
        public virtual Cat_Nom_Estados Cat_Nom_Estados { get; set; }
        public virtual Cat_Nom_Paises Cat_Nom_Paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Pos_Accesos> Apl_Pos_Accesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Parametros_Facturas> Apl_Parametros_Facturas { get; set; }
    }
}
