//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Usuarios_Notificaciones
    {
        public int Usuario_Notif_ID { get; set; }
        public int Notificacion_ID { get; set; }
        public Nullable<int> Usuario_ID { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> Fecha_Reviso { get; set; }
        public string Usuario_Creo { get; set; }
        public System.DateTime Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
    
        public virtual Apl_Notificaciones Apl_Notificaciones { get; set; }
        public virtual Apl_Usuarios Apl_Usuarios { get; set; }
    }
}
