//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Parametros_Facturas
    {
        public int Parametro_Fac_ID { get; set; }
        public int Empresa_ID { get; set; }
        public string Email_Origen_Correos { get; set; }
        public string Regimen_Fiscal { get; set; }
        public string Version { get; set; }
        public string Codigo_Usuario { get; set; }
        public string Codigo_Usuario_Proveedor { get; set; }
        public string Sucursal_ID { get; set; }
        public string Ambiente_Timbrado { get; set; }
        public string Ruta_Certificado { get; set; }
        public string Ruta_Llave { get; set; }
        public string Ruta_PDF { get; set; }
        public string Ruta_XML { get; set; }
        public Nullable<int> Aviso_Expira_Vigencia { get; set; }
        public Nullable<int> Aviso_Expira_Folios { get; set; }
        public Nullable<System.DateTime> Vigencia_Certificado_Inicio { get; set; }
        public Nullable<System.DateTime> Vigencia_Certificado_Fin { get; set; }
        public string Password_Llave { get; set; }
        public string Imagen_Factura { get; set; }
        public string Envio_Automatico_Correo { get; set; }
        public Nullable<int> Quitar_Tiempo_Timbrado { get; set; }
        public string Ruta_Externa_XML { get; set; }
        public string Ruta_Externa_PDF { get; set; }
        public string Imagen_Factura_2 { get; set; }
        public Nullable<int> Dias_Tolerancia { get; set; }
        public string Imagen_Factura_3 { get; set; }
        public string Imagen_Factura_4 { get; set; }
        public string Permitir_Facturas_Anteriores { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public Nullable<decimal> Porcentaje_Retencion_Cedular { get; set; }
        public Nullable<decimal> Porcentaje_Retencion_ISR { get; set; }
        public Nullable<decimal> Porcentaje_Retencion_IVA { get; set; }
        public Nullable<decimal> Porcentaje_Retencion_Flete { get; set; }
        public Nullable<int> Porcentaje_Efectivo_Fac { get; set; }
        public Nullable<int> Regimen_Fiscal_ID { get; set; }
    
        public virtual Apl_Empresas Apl_Empresas { get; set; }
        public virtual Cat_Nom_Regimen_Fiscal Cat_Nom_Regimen_Fiscal { get; set; }
    }
}
