//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Cat_Metodo_Pago
    {
        public int Metodo_Pago_ID { get; set; }
        public string Nombre { get; set; }
        public string No_Cuenta_Pago { get; set; }
        public string Estatus { get; set; }
        public string Descripcion { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public string Clave_SAT { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio_Vigencia { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Vigencia { get; set; }
    }
}
