//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Pos_Accesos
    {
        public int Pos_Acceso_ID { get; set; }
        public int Rol_ID { get; set; }
        public int Sys_Acceso_ID { get; set; }
        public Nullable<int> Acceso_Padre_ID { get; set; }
        public int Empresa_ID { get; set; }
        public int Sucursal_ID { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public string Habilitado { get; set; }
        public string Alta { get; set; }
        public string Cambio { get; set; }
        public string Eliminar { get; set; }
        public string Consultar { get; set; }
        public string Estatus { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Nombre_Menu { get; set; }
        public string Tipo_Menu { get; set; }
    
        public virtual Apl_Empresas Apl_Empresas { get; set; }
        public virtual Apl_Roles Apl_Roles { get; set; }
        public virtual Apl_Sucursales Apl_Sucursales { get; set; }
        public virtual Sys_Accesos Sys_Accesos { get; set; }
    }
}
