//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Cat_Bancos
    {
        public int Banco_ID { get; set; }
        public int Empresa_ID { get; set; }
        public int Sucursal_ID { get; set; }
        public Nullable<int> Banco_Sat_ID { get; set; }
        public Nullable<int> Cuenta_Contable_ID { get; set; }
        public Nullable<int> Cuenta_Contable_ID_Proveedor { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public string Cuenta { get; set; }
        public string Tipo_Moneda { get; set; }
        public string Estatus { get; set; }
        public string Calle { get; set; }
        public string No_Interior { get; set; }
        public string No_Exterior { get; set; }
        public string Colonia { get; set; }
        public string Ciudad { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public Nullable<int> Codigo_Postal { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Contacto { get; set; }
        public string Comentarios { get; set; }
        public string Usuario_Creo { get; set; }
        public System.DateTime Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
    
        public virtual Cat_Sat_Bancos Cat_Sat_Bancos { get; set; }
        public virtual Ope_Con_Cuentas_Contables_Centro_Costo Ope_Con_Cuentas_Contables_Centro_Costo { get; set; }
        public virtual Ope_Con_Cuentas_Contables_Centro_Costo Ope_Con_Cuentas_Contables_Centro_Costo1 { get; set; }
        public virtual Apl_Sucursales Apl_Sucursales { get; set; }
    }
}
