//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Avisos
    {
        public int Aviso_ID { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio_Vigencia { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Vigencia { get; set; }
    }
}
