//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Sucursales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apl_Sucursales()
        {
            this.Apl_Cat_Bancos = new HashSet<Apl_Cat_Bancos>();
            this.Apl_Notificaciones = new HashSet<Apl_Notificaciones>();
            this.Apl_Pos_Accesos = new HashSet<Apl_Pos_Accesos>();
            this.Apl_Rel_Usuarios_Roles = new HashSet<Apl_Rel_Usuarios_Roles>();
            this.Apl_Rel_Usuarios_Roles1 = new HashSet<Apl_Rel_Usuarios_Roles>();
            this.Apl_Roles = new HashSet<Apl_Roles>();
            this.Apl_Roles_Sucursales = new HashSet<Apl_Roles_Sucursales>();
            this.Tra_Cat_Config_Items_Table_Show = new HashSet<Tra_Cat_Config_Items_Table_Show>();
            this.Cat_Con_Cuentas_Contables = new HashSet<Cat_Con_Cuentas_Contables>();
            this.Cat_Con_Cuentas_Contables_Sat = new HashSet<Cat_Con_Cuentas_Contables_Sat>();
            this.Apl_Usuarios_Password = new HashSet<Apl_Usuarios_Password>();
            this.Apl_Usuarios = new HashSet<Apl_Usuarios>();
            this.Cat_Nom_Regimen_Fiscal = new HashSet<Cat_Nom_Regimen_Fiscal>();
            this.Cat_Con_Niveles = new HashSet<Cat_Con_Niveles>();
            this.Ope_Con_Cuentas_Contables_Centro_Costo = new HashSet<Ope_Con_Cuentas_Contables_Centro_Costo>();
            this.Cat_Nom_Departamentos = new HashSet<Cat_Nom_Departamentos>();
            this.Cat_Nom_Departamentos1 = new HashSet<Cat_Nom_Departamentos>();
            this.Cat_Con_Centro_Costos = new HashSet<Cat_Con_Centro_Costos>();
        }
    
        public int Empresa_ID { get; set; }
        public int Sucursal_ID { get; set; }
        public int Estatus_ID { get; set; }
        public string Nombre { get; set; }
        public string Clave { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public string RFC { get; set; }
        public string CP { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Descripcion { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Cat_Bancos> Apl_Cat_Bancos { get; set; }
        public virtual Apl_Empresas Apl_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Notificaciones> Apl_Notificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Pos_Accesos> Apl_Pos_Accesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Rel_Usuarios_Roles> Apl_Rel_Usuarios_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Rel_Usuarios_Roles> Apl_Rel_Usuarios_Roles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Roles> Apl_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Roles_Sucursales> Apl_Roles_Sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tra_Cat_Config_Items_Table_Show> Tra_Cat_Config_Items_Table_Show { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Cuentas_Contables> Cat_Con_Cuentas_Contables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Cuentas_Contables_Sat> Cat_Con_Cuentas_Contables_Sat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Usuarios_Password> Apl_Usuarios_Password { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Usuarios> Apl_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Nom_Regimen_Fiscal> Cat_Nom_Regimen_Fiscal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Niveles> Cat_Con_Niveles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Con_Cuentas_Contables_Centro_Costo> Ope_Con_Cuentas_Contables_Centro_Costo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Nom_Departamentos> Cat_Nom_Departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Nom_Departamentos> Cat_Nom_Departamentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Centro_Costos> Cat_Con_Centro_Costos { get; set; }
    }
}
