//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Rel_Usuarios_Procesos_Sistema
    {
        public int Relacion_ID { get; set; }
        public int Usuario_ID { get; set; }
        public int Proceso_ID { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
    
        public virtual Apl_Usuarios Apl_Usuarios { get; set; }
        public virtual Cat_Procesos_Sistema Cat_Procesos_Sistema { get; set; }
    }
}
