//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Con_Clientes_Cuentas_Contables_CC
    {
        public int Cliente_CCCC_ID { get; set; }
        public int Cliente_ID { get; set; }
        public int No_CCCC { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public string Operacion { get; set; }
    
        public virtual Ope_Con_Cuentas_Contables_Centro_Costo Ope_Con_Cuentas_Contables_Centro_Costo { get; set; }
    }
}
