//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Nom_Regimen_Fiscal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Nom_Regimen_Fiscal()
        {
            this.Apl_Parametros_Facturas = new HashSet<Apl_Parametros_Facturas>();
        }
    
        public int Regimen_Fiscal_ID { get; set; }
        public int Empresa_ID { get; set; }
        public int Sucursal_ID { get; set; }
        public string Clave_SAT { get; set; }
        public string Descripcion { get; set; }
        public string Estatus { get; set; }
        public string Comentarios { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public string Fisica { get; set; }
        public string Moral { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio_Vigencia { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Vigencia { get; set; }
    
        public virtual Apl_Empresas Apl_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Parametros_Facturas> Apl_Parametros_Facturas { get; set; }
        public virtual Apl_Sucursales Apl_Sucursales { get; set; }
    }
}
