//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Con_Cuentas_Contables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Con_Cuentas_Contables()
        {
            this.Cat_Con_Cuentas_Contables1 = new HashSet<Cat_Con_Cuentas_Contables>();
            this.Ope_Con_Cuentas_Contables_Centro_Costo = new HashSet<Ope_Con_Cuentas_Contables_Centro_Costo>();
        }
    
        public int Cuenta_Contable_ID { get; set; }
        public Nullable<int> Cuenta_Contable_ID_Sat { get; set; }
        public Nullable<int> Empresa_ID { get; set; }
        public Nullable<int> Sucursal_ID { get; set; }
        public string Cuenta_Contable { get; set; }
        public string Clave { get; set; }
        public string Naturaleza_Cuenta { get; set; }
        public string Estatus { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public string Afectable { get; set; }
        public Nullable<int> Cuenta_Contable_Padre_ID { get; set; }
        public Nullable<decimal> Saldo_Inicial { get; set; }
        public string Tipo_Moneda { get; set; }
        public Nullable<int> Nivel_ID { get; set; }
    
        public virtual Apl_Empresas Apl_Empresas { get; set; }
        public virtual Apl_Sucursales Apl_Sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Cuentas_Contables> Cat_Con_Cuentas_Contables1 { get; set; }
        public virtual Cat_Con_Cuentas_Contables Cat_Con_Cuentas_Contables2 { get; set; }
        public virtual Cat_Con_Cuentas_Contables_Sat Cat_Con_Cuentas_Contables_Sat { get; set; }
        public virtual Cat_Con_Niveles Cat_Con_Niveles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Con_Cuentas_Contables_Centro_Costo> Ope_Con_Cuentas_Contables_Centro_Costo { get; set; }
    }
}
