//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Con_Impuestos_Cuentas_Contables_CC
    {
        public int Impuesto_CCCC_ID { get; set; }
        public int Tipo_Impuesto_ID { get; set; }
        public int Empresa_ID { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public Nullable<int> Impuesto_Acreditable { get; set; }
        public Nullable<int> Impuesto_Por_Acreditar { get; set; }
        public Nullable<int> Impuesto_Trasladado { get; set; }
        public Nullable<int> Impuesto_Por_Trasladar { get; set; }
    
        public virtual Apl_Empresas Apl_Empresas { get; set; }
        public virtual Ope_Con_Cuentas_Contables_Centro_Costo Ope_Con_Cuentas_Contables_Centro_Costo { get; set; }
        public virtual Ope_Con_Cuentas_Contables_Centro_Costo Ope_Con_Cuentas_Contables_Centro_Costo1 { get; set; }
        public virtual Ope_Con_Cuentas_Contables_Centro_Costo Ope_Con_Cuentas_Contables_Centro_Costo2 { get; set; }
        public virtual Ope_Con_Cuentas_Contables_Centro_Costo Ope_Con_Cuentas_Contables_Centro_Costo3 { get; set; }
    }
}
