//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Nom_Codigos_Postales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Nom_Codigos_Postales()
        {
            this.Apl_Empresas = new HashSet<Apl_Empresas>();
        }
    
        public int Codigo_Postal_ID { get; set; }
        public int Estado_ID { get; set; }
        public string Clave_SAT { get; set; }
        public string Clave_Municipio { get; set; }
        public string Clave_Localidad { get; set; }
        public string Estatus { get; set; }
        public string Comentarios { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public string Codigo_Postal { get; set; }
        public Nullable<int> Localidad_ID { get; set; }
        public Nullable<int> Municipio_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Empresas> Apl_Empresas { get; set; }
        public virtual Cat_Nom_Municipios_Localidades Cat_Nom_Municipios_Localidades { get; set; }
        public virtual Cat_Nom_Estados Cat_Nom_Estados { get; set; }
        public virtual Cat_Nom_Localidades Cat_Nom_Localidades { get; set; }
    }
}
