//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Participantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Participantes()
        {
            this.Cat_Participantes_Adjuntos = new HashSet<Cat_Participantes_Adjuntos>();
            this.Cat_Relacion_Participante_Vehiculo = new HashSet<Cat_Relacion_Participante_Vehiculo>();
            this.Ope_Eventos_Vehiculo_Participante = new HashSet<Ope_Eventos_Vehiculo_Participante>();
            this.Ope_Eventos_Vehiculo_Participante1 = new HashSet<Ope_Eventos_Vehiculo_Participante>();
        }
    
        public int Participante_ID { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Estado_ID { get; set; }
        public Nullable<int> Municipio_ID { get; set; }
        public string Estatus { get; set; }
        public string Notas { get; set; }
        public string Sexo { get; set; }
        public string Colonia { get; set; }
        public string Nacionalidad { get; set; }
        public string Celular { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Participantes_Adjuntos> Cat_Participantes_Adjuntos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Relacion_Participante_Vehiculo> Cat_Relacion_Participante_Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Vehiculo_Participante> Ope_Eventos_Vehiculo_Participante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Vehiculo_Participante> Ope_Eventos_Vehiculo_Participante1 { get; set; }
    }
}
