//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ope_Eventos_Puntos_Control
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ope_Eventos_Puntos_Control()
        {
            this.Ope_Eventos_Pnt_Ctrl_Categ_Tiempos = new HashSet<Ope_Eventos_Pnt_Ctrl_Categ_Tiempos>();
            this.Ope_Eventos_Pnt_Ctrl_Operador = new HashSet<Ope_Eventos_Pnt_Ctrl_Operador>();
            this.Ope_Eventos_Sincronizacion = new HashSet<Ope_Eventos_Sincronizacion>();
            this.Ope_Eventos_Registro_Tiempo = new HashSet<Ope_Eventos_Registro_Tiempo>();
        }
    
        public int Punto_Control_Id { get; set; }
        public int Jornada_Id { get; set; }
        public int Evento_Id { get; set; }
        public string Clave { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora_Inicio { get; set; }
        public Nullable<System.TimeSpan> Hora_Fin { get; set; }
        public string Ubicacion { get; set; }
        public string Renglon { get; set; }
        public string Distancia { get; set; }
        public string Seña { get; set; }
        public Nullable<System.TimeSpan> Tiempo_Ideal { get; set; }
        public Nullable<System.TimeSpan> Intervalo { get; set; }
        public string Usuario_Cancelo { get; set; }
        public string Comentarios { get; set; }
        public Nullable<bool> Sincronizacion { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
    
        public virtual Ope_Eventos Ope_Eventos { get; set; }
        public virtual Ope_Eventos_Jornadas Ope_Eventos_Jornadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Pnt_Ctrl_Categ_Tiempos> Ope_Eventos_Pnt_Ctrl_Categ_Tiempos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Pnt_Ctrl_Operador> Ope_Eventos_Pnt_Ctrl_Operador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Sincronizacion> Ope_Eventos_Sincronizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Registro_Tiempo> Ope_Eventos_Registro_Tiempo { get; set; }
    }
}
