//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ope_Eventos_Categorias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ope_Eventos_Categorias()
        {
            this.Ope_Eventos_Registro_Tiempo = new HashSet<Ope_Eventos_Registro_Tiempo>();
            this.Ope_Eventos_Pnt_Ctrl_Categ_Tiempos = new HashSet<Ope_Eventos_Pnt_Ctrl_Categ_Tiempos>();
            this.Ope_Eventos_Vehiculo_Participante = new HashSet<Ope_Eventos_Vehiculo_Participante>();
            this.Ope_Eventos_Vehiculo_Participante1 = new HashSet<Ope_Eventos_Vehiculo_Participante>();
        }
    
        public int Categoria_Id { get; set; }
        public int Evento_Id { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Folio_Inicio { get; set; }
        public Nullable<int> Folio_Fin { get; set; }
        public Nullable<int> Año_Desde { get; set; }
        public Nullable<int> Año_Hasta { get; set; }
        public string Estatus { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
    
        public virtual Ope_Eventos Ope_Eventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Registro_Tiempo> Ope_Eventos_Registro_Tiempo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Pnt_Ctrl_Categ_Tiempos> Ope_Eventos_Pnt_Ctrl_Categ_Tiempos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Vehiculo_Participante> Ope_Eventos_Vehiculo_Participante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Vehiculo_Participante> Ope_Eventos_Vehiculo_Participante1 { get; set; }
    }
}
