//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ope_Eventos_Pnt_Ctrl_Categ_Tiempos
    {
        public int Relacion_Id { get; set; }
        public int Punto_Control_Id { get; set; }
        public int Categoria_Id { get; set; }
        public Nullable<System.TimeSpan> Tiempo_IDeal { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
    
        public virtual Ope_Eventos_Categorias Ope_Eventos_Categorias { get; set; }
        public virtual Ope_Eventos_Puntos_Control Ope_Eventos_Puntos_Control { get; set; }
    }
}
