//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ope_Eventos_Pnt_Ctrl_Operador
    {
        public int Relacion_Operador_Id { get; set; }
        public int Responsable_Id { get; set; }
        public int Punto_Control_Id { get; set; }
        public int Evento_Id { get; set; }
        public string Estatus { get; set; }
        public string Cargo { get; set; }
        public Nullable<System.TimeSpan> Hora_Llegada { get; set; }
        public Nullable<System.TimeSpan> Hora_Salida { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
    
        public virtual Cat_Responsables Cat_Responsables { get; set; }
        public virtual Ope_Eventos Ope_Eventos { get; set; }
        public virtual Ope_Eventos_Puntos_Control Ope_Eventos_Puntos_Control { get; set; }
    }
}
