//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ope_Eventos_Sincronizacion
    {
        public int Id { get; set; }
        public int Vehiculo_Participante_Id { get; set; }
        public int Punto_Control_Id { get; set; }
        public int Id_Usuario_Creo { get; set; }
        public Nullable<System.TimeSpan> Tiempo_Registrado { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
    
        public virtual Cat_Responsables Cat_Responsables { get; set; }
        public virtual Ope_Eventos_Puntos_Control Ope_Eventos_Puntos_Control { get; set; }
        public virtual Ope_Eventos_Vehiculo_Participante Ope_Eventos_Vehiculo_Participante { get; set; }
    }
}
