//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ope_Eventos_Horas_Zero
    {
        public int Hora_Id { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int Evento_Id { get; set; }
        public int Jornada_Id { get; set; }
        public int Categoria_Id { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
    
        public virtual Ope_Eventos_Jornadas Ope_Eventos_Jornadas { get; set; }
    }
}
