//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ope_Eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ope_Eventos()
        {
            this.Ope_Eventos_Registro_Tiempo = new HashSet<Ope_Eventos_Registro_Tiempo>();
            this.Ope_Eventos_Actividades = new HashSet<Ope_Eventos_Actividades>();
            this.Ope_Eventos_Categorias = new HashSet<Ope_Eventos_Categorias>();
            this.Ope_Eventos_Pnt_Ctrl_Operador = new HashSet<Ope_Eventos_Pnt_Ctrl_Operador>();
            this.Ope_Eventos_Puntos_Control = new HashSet<Ope_Eventos_Puntos_Control>();
            this.Ope_Eventos_Redes_Sociales = new HashSet<Ope_Eventos_Redes_Sociales>();
            this.Ope_Eventos_Vehiculo_Participante = new HashSet<Ope_Eventos_Vehiculo_Participante>();
        }
    
        public int Evento_Id { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public Nullable<System.DateTime> Fecha_Salida { get; set; }
        public Nullable<decimal> Recorrido { get; set; }
        public string Punto_Salida { get; set; }
        public string Punto_Meta { get; set; }
        public Nullable<System.TimeSpan> Hora_Salida { get; set; }
        public Nullable<System.TimeSpan> Intervalo { get; set; }
        public Nullable<System.TimeSpan> Intervalo_Salida { get; set; }
        public string Comentarios { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Registro_Tiempo> Ope_Eventos_Registro_Tiempo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Actividades> Ope_Eventos_Actividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Categorias> Ope_Eventos_Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Pnt_Ctrl_Operador> Ope_Eventos_Pnt_Ctrl_Operador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Puntos_Control> Ope_Eventos_Puntos_Control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Redes_Sociales> Ope_Eventos_Redes_Sociales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Eventos_Vehiculo_Participante> Ope_Eventos_Vehiculo_Participante { get; set; }
    }
}
