//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ope_Con_Cuentas_Contables_Centro_Costo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ope_Con_Cuentas_Contables_Centro_Costo()
        {
            this.Apl_Cat_Bancos = new HashSet<Apl_Cat_Bancos>();
            this.Apl_Cat_Bancos1 = new HashSet<Apl_Cat_Bancos>();
            this.Cat_Con_Clientes_Cuentas_Contables_CC = new HashSet<Cat_Con_Clientes_Cuentas_Contables_CC>();
            this.Cat_Con_Impuestos_Cuentas_Contables_CC = new HashSet<Cat_Con_Impuestos_Cuentas_Contables_CC>();
            this.Cat_Con_Impuestos_Cuentas_Contables_CC1 = new HashSet<Cat_Con_Impuestos_Cuentas_Contables_CC>();
            this.Cat_Con_Impuestos_Cuentas_Contables_CC2 = new HashSet<Cat_Con_Impuestos_Cuentas_Contables_CC>();
            this.Cat_Con_Impuestos_Cuentas_Contables_CC3 = new HashSet<Cat_Con_Impuestos_Cuentas_Contables_CC>();
        }
    
        public int No_CCCC { get; set; }
        public Nullable<int> Empresa_ID { get; set; }
        public Nullable<int> Sucursal_ID { get; set; }
        public Nullable<int> Cuenta_Contable_ID { get; set; }
        public string Cuenta_Contable { get; set; }
        public string Cuenta_Contable_CC { get; set; }
        public Nullable<int> Nivel_ID { get; set; }
        public string Estatus { get; set; }
        public string Usuario_Creo { get; set; }
        public System.DateTime Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public Nullable<int> Centro_Costo_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Cat_Bancos> Apl_Cat_Bancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Cat_Bancos> Apl_Cat_Bancos1 { get; set; }
        public virtual Apl_Sucursales Apl_Sucursales { get; set; }
        public virtual Cat_Con_Centro_Costos Cat_Con_Centro_Costos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Clientes_Cuentas_Contables_CC> Cat_Con_Clientes_Cuentas_Contables_CC { get; set; }
        public virtual Cat_Con_Cuentas_Contables Cat_Con_Cuentas_Contables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Impuestos_Cuentas_Contables_CC> Cat_Con_Impuestos_Cuentas_Contables_CC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Impuestos_Cuentas_Contables_CC> Cat_Con_Impuestos_Cuentas_Contables_CC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Impuestos_Cuentas_Contables_CC> Cat_Con_Impuestos_Cuentas_Contables_CC2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Con_Impuestos_Cuentas_Contables_CC> Cat_Con_Impuestos_Cuentas_Contables_CC3 { get; set; }
        public virtual Cat_Con_Niveles Cat_Con_Niveles { get; set; }
    }
}
