//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tra_Cat_Estructura_Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tra_Cat_Estructura_Productos()
        {
            this.Tra_Cat_Estructura_Productos1 = new HashSet<Tra_Cat_Estructura_Productos>();
        }
    
        public int Estructura_Producto_ID { get; set; }
        public Nullable<int> Estructura_Producto_Padre_ID { get; set; }
        public int Material_ID { get; set; }
        public int Empresa_ID { get; set; }
        public int Unidad_ID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public Nullable<double> Duracion { get; set; }
    
        public virtual Apl_Empresas Apl_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tra_Cat_Estructura_Productos> Tra_Cat_Estructura_Productos1 { get; set; }
        public virtual Tra_Cat_Estructura_Productos Tra_Cat_Estructura_Productos2 { get; set; }
        public virtual Tra_Cat_Unidades Tra_Cat_Unidades { get; set; }
    }
}
