//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_trazabilidad.Paginas.Paginas_Generales
{


    public partial class Frm_Tra_Cat_Config_Items_Table_Show
    {
    }
}
