//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_trazabilidad.FacturacionContel_33 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametrosEntradaWSTimbrado", Namespace="http://schemas.datacontract.org/2004/07/WCFWSTimbrado")]
    [System.SerializableAttribute()]
    public partial class ParametrosEntradaWSTimbrado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAddendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdLlaveUnicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailCCOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailParaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodoAddendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLOpcionalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLPreCFDIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAddenda {
            get {
                return this.IdAddendaField;
            }
            set {
                if ((this.IdAddendaField.Equals(value) != true)) {
                    this.IdAddendaField = value;
                    this.RaisePropertyChanged("IdAddenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdLlaveUnico {
            get {
                return this.IdLlaveUnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdLlaveUnicoField, value) != true)) {
                    this.IdLlaveUnicoField = value;
                    this.RaisePropertyChanged("IdLlaveUnico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailCC {
            get {
                return this.MailCCField;
            }
            set {
                if ((object.ReferenceEquals(this.MailCCField, value) != true)) {
                    this.MailCCField = value;
                    this.RaisePropertyChanged("MailCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailCCO {
            get {
                return this.MailCCOField;
            }
            set {
                if ((object.ReferenceEquals(this.MailCCOField, value) != true)) {
                    this.MailCCOField = value;
                    this.RaisePropertyChanged("MailCCO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailPara {
            get {
                return this.MailParaField;
            }
            set {
                if ((object.ReferenceEquals(this.MailParaField, value) != true)) {
                    this.MailParaField = value;
                    this.RaisePropertyChanged("MailPara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodoAddenda {
            get {
                return this.NodoAddendaField;
            }
            set {
                if ((object.ReferenceEquals(this.NodoAddendaField, value) != true)) {
                    this.NodoAddendaField = value;
                    this.RaisePropertyChanged("NodoAddenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUIDSucursal {
            get {
                return this.UUIDSucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDSucursalField, value) != true)) {
                    this.UUIDSucursalField = value;
                    this.RaisePropertyChanged("UUIDSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLOpcionales {
            get {
                return this.XMLOpcionalesField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLOpcionalesField, value) != true)) {
                    this.XMLOpcionalesField = value;
                    this.RaisePropertyChanged("XMLOpcionales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLPreCFDI {
            get {
                return this.XMLPreCFDIField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLPreCFDIField, value) != true)) {
                    this.XMLPreCFDIField = value;
                    this.RaisePropertyChanged("XMLPreCFDI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametrosSalidaWSTimbrado", Namespace="http://schemas.datacontract.org/2004/07/WCFWSTimbrado")]
    [System.SerializableAttribute()]
    public partial class ParametrosSalidaWSTimbrado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstatusRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdValidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeValidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaPDFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sugerencias3BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Validacion3BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLTimbradoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstatusRespuesta {
            get {
                return this.EstatusRespuestaField;
            }
            set {
                if ((this.EstatusRespuestaField.Equals(value) != true)) {
                    this.EstatusRespuestaField = value;
                    this.RaisePropertyChanged("EstatusRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioFiscal {
            get {
                return this.FolioFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioFiscalField, value) != true)) {
                    this.FolioFiscalField = value;
                    this.RaisePropertyChanged("FolioFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdValidacion {
            get {
                return this.IdValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdValidacionField, value) != true)) {
                    this.IdValidacionField = value;
                    this.RaisePropertyChanged("IdValidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeValidacion {
            get {
                return this.MensajeValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeValidacionField, value) != true)) {
                    this.MensajeValidacionField = value;
                    this.RaisePropertyChanged("MensajeValidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaPDF {
            get {
                return this.RutaPDFField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaPDFField, value) != true)) {
                    this.RutaPDFField = value;
                    this.RaisePropertyChanged("RutaPDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sugerencias3B {
            get {
                return this.Sugerencias3BField;
            }
            set {
                if ((object.ReferenceEquals(this.Sugerencias3BField, value) != true)) {
                    this.Sugerencias3BField = value;
                    this.RaisePropertyChanged("Sugerencias3B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Validacion3B {
            get {
                return this.Validacion3BField;
            }
            set {
                if ((object.ReferenceEquals(this.Validacion3BField, value) != true)) {
                    this.Validacion3BField = value;
                    this.RaisePropertyChanged("Validacion3B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLTimbrado {
            get {
                return this.XMLTimbradoField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLTimbradoField, value) != true)) {
                    this.XMLTimbradoField = value;
                    this.RaisePropertyChanged("XMLTimbrado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametrosEntradaWSCancelacion", Namespace="http://schemas.datacontract.org/2004/07/WCFWSTimbrado")]
    [System.SerializableAttribute()]
    public partial class ParametrosEntradaWSCancelacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioFiscal {
            get {
                return this.FolioFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioFiscalField, value) != true)) {
                    this.FolioFiscalField = value;
                    this.RaisePropertyChanged("FolioFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCEmisor {
            get {
                return this.RFCEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCEmisorField, value) != true)) {
                    this.RFCEmisorField = value;
                    this.RaisePropertyChanged("RFCEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametrosSalidaWSCancelacion", Namespace="http://schemas.datacontract.org/2004/07/WCFWSTimbrado")]
    [System.SerializableAttribute()]
    public partial class ParametrosSalidaWSCancelacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstatusRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdValidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeValidacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstatusRespuesta {
            get {
                return this.EstatusRespuestaField;
            }
            set {
                if ((this.EstatusRespuestaField.Equals(value) != true)) {
                    this.EstatusRespuestaField = value;
                    this.RaisePropertyChanged("EstatusRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdValidacion {
            get {
                return this.IdValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdValidacionField, value) != true)) {
                    this.IdValidacionField = value;
                    this.RaisePropertyChanged("IdValidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeValidacion {
            get {
                return this.MensajeValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeValidacionField, value) != true)) {
                    this.MensajeValidacionField = value;
                    this.RaisePropertyChanged("MensajeValidacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametrosEntradaRecuperacionCFDI", Namespace="http://schemas.datacontract.org/2004/07/WCFWSTimbrado")]
    [System.SerializableAttribute()]
    public partial class ParametrosEntradaRecuperacionCFDI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLPreCFDIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioFiscal {
            get {
                return this.FolioFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioFiscalField, value) != true)) {
                    this.FolioFiscalField = value;
                    this.RaisePropertyChanged("FolioFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLPreCFDI {
            get {
                return this.XMLPreCFDIField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLPreCFDIField, value) != true)) {
                    this.XMLPreCFDIField = value;
                    this.RaisePropertyChanged("XMLPreCFDI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametrosSalidaRecuperacionCFDI", Namespace="http://schemas.datacontract.org/2004/07/WCFWSTimbrado")]
    [System.SerializableAttribute()]
    public partial class ParametrosSalidaRecuperacionCFDI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstatusCFDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstatusRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdValidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeValidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLCFDIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstatusCFDI {
            get {
                return this.EstatusCFDIField;
            }
            set {
                if ((this.EstatusCFDIField.Equals(value) != true)) {
                    this.EstatusCFDIField = value;
                    this.RaisePropertyChanged("EstatusCFDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstatusRespuesta {
            get {
                return this.EstatusRespuestaField;
            }
            set {
                if ((this.EstatusRespuestaField.Equals(value) != true)) {
                    this.EstatusRespuestaField = value;
                    this.RaisePropertyChanged("EstatusRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdValidacion {
            get {
                return this.IdValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdValidacionField, value) != true)) {
                    this.IdValidacionField = value;
                    this.RaisePropertyChanged("IdValidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeValidacion {
            get {
                return this.MensajeValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeValidacionField, value) != true)) {
                    this.MensajeValidacionField = value;
                    this.RaisePropertyChanged("MensajeValidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLCFDI {
            get {
                return this.XMLCFDIField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLCFDIField, value) != true)) {
                    this.XMLCFDIField = value;
                    this.RaisePropertyChanged("XMLCFDI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametrosEntradaRecuperacionAcuseCancelacion", Namespace="http://schemas.datacontract.org/2004/07/WCFWSTimbrado")]
    [System.SerializableAttribute()]
    public partial class ParametrosEntradaRecuperacionAcuseCancelacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioFiscal {
            get {
                return this.FolioFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioFiscalField, value) != true)) {
                    this.FolioFiscalField = value;
                    this.RaisePropertyChanged("FolioFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCEmisor {
            get {
                return this.RFCEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCEmisorField, value) != true)) {
                    this.RFCEmisorField = value;
                    this.RaisePropertyChanged("RFCEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametrosSalidaRecuperacionAcuseCancelacion", Namespace="http://schemas.datacontract.org/2004/07/WCFWSTimbrado")]
    [System.SerializableAttribute()]
    public partial class ParametrosSalidaRecuperacionAcuseCancelacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcuseCancelacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstatusRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdValidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeValidacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcuseCancelacion {
            get {
                return this.AcuseCancelacionField;
            }
            set {
                if ((object.ReferenceEquals(this.AcuseCancelacionField, value) != true)) {
                    this.AcuseCancelacionField = value;
                    this.RaisePropertyChanged("AcuseCancelacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstatusRespuesta {
            get {
                return this.EstatusRespuestaField;
            }
            set {
                if ((this.EstatusRespuestaField.Equals(value) != true)) {
                    this.EstatusRespuestaField = value;
                    this.RaisePropertyChanged("EstatusRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdValidacion {
            get {
                return this.IdValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdValidacionField, value) != true)) {
                    this.IdValidacionField = value;
                    this.RaisePropertyChanged("IdValidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeValidacion {
            get {
                return this.MensajeValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeValidacionField, value) != true)) {
                    this.MensajeValidacionField = value;
                    this.RaisePropertyChanged("MensajeValidacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacturacionContel_33.IWSTimbrado")]
    public interface IWSTimbrado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/TimbrarObjeto", ReplyAction="http://tempuri.org/IWSTimbrado/TimbrarObjetoResponse")]
        web_trazabilidad.FacturacionContel_33.ParametrosSalidaWSTimbrado TimbrarObjeto(web_trazabilidad.FacturacionContel_33.ParametrosEntradaWSTimbrado parametrosEntradaWSTimbrado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/TimbrarObjeto", ReplyAction="http://tempuri.org/IWSTimbrado/TimbrarObjetoResponse")]
        System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.ParametrosSalidaWSTimbrado> TimbrarObjetoAsync(web_trazabilidad.FacturacionContel_33.ParametrosEntradaWSTimbrado parametrosEntradaWSTimbrado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/TimbrarParametros", ReplyAction="http://tempuri.org/IWSTimbrado/TimbrarParametrosResponse")]
        web_trazabilidad.FacturacionContel_33.TimbrarParametrosResponse TimbrarParametros(web_trazabilidad.FacturacionContel_33.TimbrarParametrosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/TimbrarParametros", ReplyAction="http://tempuri.org/IWSTimbrado/TimbrarParametrosResponse")]
        System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.TimbrarParametrosResponse> TimbrarParametrosAsync(web_trazabilidad.FacturacionContel_33.TimbrarParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/CancelarParametros", ReplyAction="http://tempuri.org/IWSTimbrado/CancelarParametrosResponse")]
        web_trazabilidad.FacturacionContel_33.CancelarParametrosResponse CancelarParametros(web_trazabilidad.FacturacionContel_33.CancelarParametrosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/CancelarParametros", ReplyAction="http://tempuri.org/IWSTimbrado/CancelarParametrosResponse")]
        System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.CancelarParametrosResponse> CancelarParametrosAsync(web_trazabilidad.FacturacionContel_33.CancelarParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/CancelarObjeto", ReplyAction="http://tempuri.org/IWSTimbrado/CancelarObjetoResponse")]
        web_trazabilidad.FacturacionContel_33.ParametrosSalidaWSCancelacion CancelarObjeto(web_trazabilidad.FacturacionContel_33.ParametrosEntradaWSCancelacion parametrosEntradaWSCancelacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/CancelarObjeto", ReplyAction="http://tempuri.org/IWSTimbrado/CancelarObjetoResponse")]
        System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.ParametrosSalidaWSCancelacion> CancelarObjetoAsync(web_trazabilidad.FacturacionContel_33.ParametrosEntradaWSCancelacion parametrosEntradaWSCancelacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/RecuperaCFDIObjeto", ReplyAction="http://tempuri.org/IWSTimbrado/RecuperaCFDIObjetoResponse")]
        web_trazabilidad.FacturacionContel_33.ParametrosSalidaRecuperacionCFDI RecuperaCFDIObjeto(web_trazabilidad.FacturacionContel_33.ParametrosEntradaRecuperacionCFDI parametrosEntradaRecuperacionCFDI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/RecuperaCFDIObjeto", ReplyAction="http://tempuri.org/IWSTimbrado/RecuperaCFDIObjetoResponse")]
        System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.ParametrosSalidaRecuperacionCFDI> RecuperaCFDIObjetoAsync(web_trazabilidad.FacturacionContel_33.ParametrosEntradaRecuperacionCFDI parametrosEntradaRecuperacionCFDI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/RecuperaCFDIParametros", ReplyAction="http://tempuri.org/IWSTimbrado/RecuperaCFDIParametrosResponse")]
        web_trazabilidad.FacturacionContel_33.RecuperaCFDIParametrosResponse RecuperaCFDIParametros(web_trazabilidad.FacturacionContel_33.RecuperaCFDIParametrosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/RecuperaCFDIParametros", ReplyAction="http://tempuri.org/IWSTimbrado/RecuperaCFDIParametrosResponse")]
        System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.RecuperaCFDIParametrosResponse> RecuperaCFDIParametrosAsync(web_trazabilidad.FacturacionContel_33.RecuperaCFDIParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/RecuperaAcuseCancelacion", ReplyAction="http://tempuri.org/IWSTimbrado/RecuperaAcuseCancelacionResponse")]
        web_trazabilidad.FacturacionContel_33.ParametrosSalidaRecuperacionAcuseCancelacion RecuperaAcuseCancelacion(web_trazabilidad.FacturacionContel_33.ParametrosEntradaRecuperacionAcuseCancelacion parametrosEntradaRecuperacionAcuseCancelacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/RecuperaAcuseCancelacion", ReplyAction="http://tempuri.org/IWSTimbrado/RecuperaAcuseCancelacionResponse")]
        System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.ParametrosSalidaRecuperacionAcuseCancelacion> RecuperaAcuseCancelacionAsync(web_trazabilidad.FacturacionContel_33.ParametrosEntradaRecuperacionAcuseCancelacion parametrosEntradaRecuperacionAcuseCancelacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/ValidaRFCSAT", ReplyAction="http://tempuri.org/IWSTimbrado/ValidaRFCSATResponse")]
        web_trazabilidad.FacturacionContel_33.ValidaRFCSATResponse ValidaRFCSAT(web_trazabilidad.FacturacionContel_33.ValidaRFCSATRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTimbrado/ValidaRFCSAT", ReplyAction="http://tempuri.org/IWSTimbrado/ValidaRFCSATResponse")]
        System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.ValidaRFCSATResponse> ValidaRFCSATAsync(web_trazabilidad.FacturacionContel_33.ValidaRFCSATRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TimbrarParametros", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TimbrarParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Contrasenia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string XMLPreCFDI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string XMLOpcionales;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int IdAddenda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string NodoAddenda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string IdLlaveUnico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string UUIDSucursal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string Mail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string MailCC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string MailCCO;
        
        public TimbrarParametrosRequest() {
        }
        
        public TimbrarParametrosRequest(string Usuario, string Contrasenia, string XMLPreCFDI, string XMLOpcionales, int IdAddenda, string NodoAddenda, string IdLlaveUnico, string UUIDSucursal, string Mail, string MailCC, string MailCCO) {
            this.Usuario = Usuario;
            this.Contrasenia = Contrasenia;
            this.XMLPreCFDI = XMLPreCFDI;
            this.XMLOpcionales = XMLOpcionales;
            this.IdAddenda = IdAddenda;
            this.NodoAddenda = NodoAddenda;
            this.IdLlaveUnico = IdLlaveUnico;
            this.UUIDSucursal = UUIDSucursal;
            this.Mail = Mail;
            this.MailCC = MailCC;
            this.MailCCO = MailCCO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TimbrarParametrosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TimbrarParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool TimbrarParametrosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string XMLCFDI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string FolioFiscal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string RutaPDF;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Validacion3B;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Sugerencias3B;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string IdValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string MensajeValidacion;
        
        public TimbrarParametrosResponse() {
        }
        
        public TimbrarParametrosResponse(bool TimbrarParametrosResult, string XMLCFDI, string FolioFiscal, string RutaPDF, string Validacion3B, string Sugerencias3B, string IdValidacion, string MensajeValidacion) {
            this.TimbrarParametrosResult = TimbrarParametrosResult;
            this.XMLCFDI = XMLCFDI;
            this.FolioFiscal = FolioFiscal;
            this.RutaPDF = RutaPDF;
            this.Validacion3B = Validacion3B;
            this.Sugerencias3B = Sugerencias3B;
            this.IdValidacion = IdValidacion;
            this.MensajeValidacion = MensajeValidacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarParametros", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelarParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Contrasenia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string RFCEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string FolioFiscal;
        
        public CancelarParametrosRequest() {
        }
        
        public CancelarParametrosRequest(string Usuario, string Contrasenia, string RFCEmisor, string FolioFiscal) {
            this.Usuario = Usuario;
            this.Contrasenia = Contrasenia;
            this.RFCEmisor = RFCEmisor;
            this.FolioFiscal = FolioFiscal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarParametrosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelarParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CancelarParametrosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string IdValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string MensajeValidacion;
        
        public CancelarParametrosResponse() {
        }
        
        public CancelarParametrosResponse(bool CancelarParametrosResult, string IdValidacion, string MensajeValidacion) {
            this.CancelarParametrosResult = CancelarParametrosResult;
            this.IdValidacion = IdValidacion;
            this.MensajeValidacion = MensajeValidacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperaCFDIParametros", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperaCFDIParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Contrasenia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string XMLPreCFDI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string FolioFiscal;
        
        public RecuperaCFDIParametrosRequest() {
        }
        
        public RecuperaCFDIParametrosRequest(string Usuario, string Contrasenia, string XMLPreCFDI, string FolioFiscal) {
            this.Usuario = Usuario;
            this.Contrasenia = Contrasenia;
            this.XMLPreCFDI = XMLPreCFDI;
            this.FolioFiscal = FolioFiscal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperaCFDIParametrosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperaCFDIParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RecuperaCFDIParametrosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string XMLCFDI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int EstatusCFDI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string IdValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string MensajeValidacion;
        
        public RecuperaCFDIParametrosResponse() {
        }
        
        public RecuperaCFDIParametrosResponse(bool RecuperaCFDIParametrosResult, string XMLCFDI, int EstatusCFDI, string IdValidacion, string MensajeValidacion) {
            this.RecuperaCFDIParametrosResult = RecuperaCFDIParametrosResult;
            this.XMLCFDI = XMLCFDI;
            this.EstatusCFDI = EstatusCFDI;
            this.IdValidacion = IdValidacion;
            this.MensajeValidacion = MensajeValidacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidaRFCSAT", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidaRFCSATRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Contrasenia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Rfc;
        
        public ValidaRFCSATRequest() {
        }
        
        public ValidaRFCSATRequest(string Usuario, string Contrasenia, string Rfc) {
            this.Usuario = Usuario;
            this.Contrasenia = Contrasenia;
            this.Rfc = Rfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidaRFCSATResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidaRFCSATResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ValidaRFCSATResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string IdValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string MensajeValidacion;
        
        public ValidaRFCSATResponse() {
        }
        
        public ValidaRFCSATResponse(bool ValidaRFCSATResult, string IdValidacion, string MensajeValidacion) {
            this.ValidaRFCSATResult = ValidaRFCSATResult;
            this.IdValidacion = IdValidacion;
            this.MensajeValidacion = MensajeValidacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSTimbradoChannel : web_trazabilidad.FacturacionContel_33.IWSTimbrado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTimbradoClient : System.ServiceModel.ClientBase<web_trazabilidad.FacturacionContel_33.IWSTimbrado>, web_trazabilidad.FacturacionContel_33.IWSTimbrado {
        
        public WSTimbradoClient() {
        }
        
        public WSTimbradoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTimbradoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTimbradoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTimbradoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public web_trazabilidad.FacturacionContel_33.ParametrosSalidaWSTimbrado TimbrarObjeto(web_trazabilidad.FacturacionContel_33.ParametrosEntradaWSTimbrado parametrosEntradaWSTimbrado) {
            return base.Channel.TimbrarObjeto(parametrosEntradaWSTimbrado);
        }
        
        public System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.ParametrosSalidaWSTimbrado> TimbrarObjetoAsync(web_trazabilidad.FacturacionContel_33.ParametrosEntradaWSTimbrado parametrosEntradaWSTimbrado) {
            return base.Channel.TimbrarObjetoAsync(parametrosEntradaWSTimbrado);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_trazabilidad.FacturacionContel_33.TimbrarParametrosResponse web_trazabilidad.FacturacionContel_33.IWSTimbrado.TimbrarParametros(web_trazabilidad.FacturacionContel_33.TimbrarParametrosRequest request) {
            return base.Channel.TimbrarParametros(request);
        }
        
        public bool TimbrarParametros(
                    string Usuario, 
                    string Contrasenia, 
                    string XMLPreCFDI, 
                    string XMLOpcionales, 
                    int IdAddenda, 
                    string NodoAddenda, 
                    string IdLlaveUnico, 
                    string UUIDSucursal, 
                    string Mail, 
                    string MailCC, 
                    string MailCCO, 
                    out string XMLCFDI, 
                    out string FolioFiscal, 
                    out string RutaPDF, 
                    out string Validacion3B, 
                    out string Sugerencias3B, 
                    out string IdValidacion, 
                    out string MensajeValidacion) {
            web_trazabilidad.FacturacionContel_33.TimbrarParametrosRequest inValue = new web_trazabilidad.FacturacionContel_33.TimbrarParametrosRequest();
            inValue.Usuario = Usuario;
            inValue.Contrasenia = Contrasenia;
            inValue.XMLPreCFDI = XMLPreCFDI;
            inValue.XMLOpcionales = XMLOpcionales;
            inValue.IdAddenda = IdAddenda;
            inValue.NodoAddenda = NodoAddenda;
            inValue.IdLlaveUnico = IdLlaveUnico;
            inValue.UUIDSucursal = UUIDSucursal;
            inValue.Mail = Mail;
            inValue.MailCC = MailCC;
            inValue.MailCCO = MailCCO;
            web_trazabilidad.FacturacionContel_33.TimbrarParametrosResponse retVal = ((web_trazabilidad.FacturacionContel_33.IWSTimbrado)(this)).TimbrarParametros(inValue);
            XMLCFDI = retVal.XMLCFDI;
            FolioFiscal = retVal.FolioFiscal;
            RutaPDF = retVal.RutaPDF;
            Validacion3B = retVal.Validacion3B;
            Sugerencias3B = retVal.Sugerencias3B;
            IdValidacion = retVal.IdValidacion;
            MensajeValidacion = retVal.MensajeValidacion;
            return retVal.TimbrarParametrosResult;
        }
        
        public System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.TimbrarParametrosResponse> TimbrarParametrosAsync(web_trazabilidad.FacturacionContel_33.TimbrarParametrosRequest request) {
            return base.Channel.TimbrarParametrosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_trazabilidad.FacturacionContel_33.CancelarParametrosResponse web_trazabilidad.FacturacionContel_33.IWSTimbrado.CancelarParametros(web_trazabilidad.FacturacionContel_33.CancelarParametrosRequest request) {
            return base.Channel.CancelarParametros(request);
        }
        
        public bool CancelarParametros(string Usuario, string Contrasenia, string RFCEmisor, string FolioFiscal, out string IdValidacion, out string MensajeValidacion) {
            web_trazabilidad.FacturacionContel_33.CancelarParametrosRequest inValue = new web_trazabilidad.FacturacionContel_33.CancelarParametrosRequest();
            inValue.Usuario = Usuario;
            inValue.Contrasenia = Contrasenia;
            inValue.RFCEmisor = RFCEmisor;
            inValue.FolioFiscal = FolioFiscal;
            web_trazabilidad.FacturacionContel_33.CancelarParametrosResponse retVal = ((web_trazabilidad.FacturacionContel_33.IWSTimbrado)(this)).CancelarParametros(inValue);
            IdValidacion = retVal.IdValidacion;
            MensajeValidacion = retVal.MensajeValidacion;
            return retVal.CancelarParametrosResult;
        }
        
        public System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.CancelarParametrosResponse> CancelarParametrosAsync(web_trazabilidad.FacturacionContel_33.CancelarParametrosRequest request) {
            return base.Channel.CancelarParametrosAsync(request);
        }
        
        public web_trazabilidad.FacturacionContel_33.ParametrosSalidaWSCancelacion CancelarObjeto(web_trazabilidad.FacturacionContel_33.ParametrosEntradaWSCancelacion parametrosEntradaWSCancelacion) {
            return base.Channel.CancelarObjeto(parametrosEntradaWSCancelacion);
        }
        
        public System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.ParametrosSalidaWSCancelacion> CancelarObjetoAsync(web_trazabilidad.FacturacionContel_33.ParametrosEntradaWSCancelacion parametrosEntradaWSCancelacion) {
            return base.Channel.CancelarObjetoAsync(parametrosEntradaWSCancelacion);
        }
        
        public web_trazabilidad.FacturacionContel_33.ParametrosSalidaRecuperacionCFDI RecuperaCFDIObjeto(web_trazabilidad.FacturacionContel_33.ParametrosEntradaRecuperacionCFDI parametrosEntradaRecuperacionCFDI) {
            return base.Channel.RecuperaCFDIObjeto(parametrosEntradaRecuperacionCFDI);
        }
        
        public System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.ParametrosSalidaRecuperacionCFDI> RecuperaCFDIObjetoAsync(web_trazabilidad.FacturacionContel_33.ParametrosEntradaRecuperacionCFDI parametrosEntradaRecuperacionCFDI) {
            return base.Channel.RecuperaCFDIObjetoAsync(parametrosEntradaRecuperacionCFDI);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_trazabilidad.FacturacionContel_33.RecuperaCFDIParametrosResponse web_trazabilidad.FacturacionContel_33.IWSTimbrado.RecuperaCFDIParametros(web_trazabilidad.FacturacionContel_33.RecuperaCFDIParametrosRequest request) {
            return base.Channel.RecuperaCFDIParametros(request);
        }
        
        public bool RecuperaCFDIParametros(string Usuario, string Contrasenia, string XMLPreCFDI, string FolioFiscal, out string XMLCFDI, out int EstatusCFDI, out string IdValidacion, out string MensajeValidacion) {
            web_trazabilidad.FacturacionContel_33.RecuperaCFDIParametrosRequest inValue = new web_trazabilidad.FacturacionContel_33.RecuperaCFDIParametrosRequest();
            inValue.Usuario = Usuario;
            inValue.Contrasenia = Contrasenia;
            inValue.XMLPreCFDI = XMLPreCFDI;
            inValue.FolioFiscal = FolioFiscal;
            web_trazabilidad.FacturacionContel_33.RecuperaCFDIParametrosResponse retVal = ((web_trazabilidad.FacturacionContel_33.IWSTimbrado)(this)).RecuperaCFDIParametros(inValue);
            XMLCFDI = retVal.XMLCFDI;
            EstatusCFDI = retVal.EstatusCFDI;
            IdValidacion = retVal.IdValidacion;
            MensajeValidacion = retVal.MensajeValidacion;
            return retVal.RecuperaCFDIParametrosResult;
        }
        
        public System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.RecuperaCFDIParametrosResponse> RecuperaCFDIParametrosAsync(web_trazabilidad.FacturacionContel_33.RecuperaCFDIParametrosRequest request) {
            return base.Channel.RecuperaCFDIParametrosAsync(request);
        }
        
        public web_trazabilidad.FacturacionContel_33.ParametrosSalidaRecuperacionAcuseCancelacion RecuperaAcuseCancelacion(web_trazabilidad.FacturacionContel_33.ParametrosEntradaRecuperacionAcuseCancelacion parametrosEntradaRecuperacionAcuseCancelacion) {
            return base.Channel.RecuperaAcuseCancelacion(parametrosEntradaRecuperacionAcuseCancelacion);
        }
        
        public System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.ParametrosSalidaRecuperacionAcuseCancelacion> RecuperaAcuseCancelacionAsync(web_trazabilidad.FacturacionContel_33.ParametrosEntradaRecuperacionAcuseCancelacion parametrosEntradaRecuperacionAcuseCancelacion) {
            return base.Channel.RecuperaAcuseCancelacionAsync(parametrosEntradaRecuperacionAcuseCancelacion);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_trazabilidad.FacturacionContel_33.ValidaRFCSATResponse web_trazabilidad.FacturacionContel_33.IWSTimbrado.ValidaRFCSAT(web_trazabilidad.FacturacionContel_33.ValidaRFCSATRequest request) {
            return base.Channel.ValidaRFCSAT(request);
        }
        
        public bool ValidaRFCSAT(string Usuario, string Contrasenia, string Rfc, out string IdValidacion, out string MensajeValidacion) {
            web_trazabilidad.FacturacionContel_33.ValidaRFCSATRequest inValue = new web_trazabilidad.FacturacionContel_33.ValidaRFCSATRequest();
            inValue.Usuario = Usuario;
            inValue.Contrasenia = Contrasenia;
            inValue.Rfc = Rfc;
            web_trazabilidad.FacturacionContel_33.ValidaRFCSATResponse retVal = ((web_trazabilidad.FacturacionContel_33.IWSTimbrado)(this)).ValidaRFCSAT(inValue);
            IdValidacion = retVal.IdValidacion;
            MensajeValidacion = retVal.MensajeValidacion;
            return retVal.ValidaRFCSATResult;
        }
        
        public System.Threading.Tasks.Task<web_trazabilidad.FacturacionContel_33.ValidaRFCSATResponse> ValidaRFCSATAsync(web_trazabilidad.FacturacionContel_33.ValidaRFCSATRequest request) {
            return base.Channel.ValidaRFCSATAsync(request);
        }
    }
}
